Adding required field: role_arn
I'm getting the following error while running the previous version:
```
Error: module.dynamodb_autoscaler.aws_appautoscaling_target.read_target: "role_arn": required field is not set
Error: module.dynamodb_autoscaler.aws_appautoscaling_target.write_target: "role_arn": required field is not set
```